# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- name: "{{ home }}/.Xresources"
  blockinfile:
    path: "{{ home }}/.Xresources"
    create: yes
    marker: '! {mark} XTERM ANSIBLE MANAGED BLOCK'
    block: |
      xterm*font: 9x15
      xterm*foreground: white
      xterm*background: black
      xterm*color1: chocolate1
      xterm*color9: chocolate1
      xterm*color12: lightskyblue
      xterm*translations: #override <Key>F9: secure()
  notify:
    - xrdb Xresources
