# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- name: monitor
  blockinfile:
    path: /etc/X11/xorg.conf.d/99-mode.conf
    create: yes
    block: |
      Section "Monitor"
        Identifier "eDP-1"
        Modeline "1920x1080_60.00"  172.80  1920 2040 2248 2576  1080 1081 1084 1118  -HSync +Vsync
        Option "PreferredMode" "1920x1080_60.00"
        DisplaySize 346 194
      EndSection
  when: ansible_product_name == 'Precision 7510'
  become: yes

- name: brightness
  lineinfile:
    path: "{{ home }}/.config/lxsession/LXDE/autostart"
    regexp: 'brightness'
    line: '@xrandr --output eDP-1 --brightness 0.55'
  when: ansible_product_name == 'Precision 7510'
