#!/usr/bin/expect -f
# ---------------------------------------------------------------------------- #
## \file test1.exp
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
spawn build/server
set server $spawn_id
sleep 1
spawn build/client

expect "client: send status"
expect -i $server "server: recv status"
expect "client: recv ok"

expect "client: send quit"
expect -i $server "server: recv quit"

expect -i $server eof
expect eof
