# ---------------------------------------------------------------------------- #
## \file Vagrantfile
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
load "../../makefiles/Vagrantfile"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.define "default"
  config.vm.hostname = "debian12"
  config.vm.provider :libvirt do |libvirt|
    libvirt.management_network_mac = "52:54:00:00:12:00"
  end
end
