# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- name: install pbuilder packages
  apt:
    cache_valid_time: 36000
    install_recommends: no
    name:
      - ubuntu-dev-tools
      - pbuilder
      - qemu-user-static
      - arch-test
      - binfmt-support
      - lintian
  become: yes
