# ---------------------------------------------------------------------------- #
## \file playbook.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- hosts: default
  vars:
    user: vagrant
    home: /home/{{ user }}
  roles:
    # Common roles
    - bashrc
    - packages-dev
    - timezone
    - rabbitmq
    - vim
    # Remote roles
    - screen-remote
    # Desktop roles
    #- lubuntu-desktop
    #- screen
    #- screensaver-off
