---
- hosts: default
  vars:
    user: vagrant
    home: /home/{{ user }}
  roles:
    - bashrc
    - packages-dev
    - timezone
    - rabbitmq
    - screen
    - vim
    #
    - lubuntu-desktop
    - screen-remote
