# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- name: emacs.el
  copy:
    src: emacs.el
    dest: "{{ home }}/.emacs"
    force: no
