# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- name: "{{ home }}/.emacs"
  copy:
    src: emacs.el
    dest: "{{ home }}/.emacs"
    force: no

- name: notify_startup_complete.py
  copy:
    src: notify_startup_complete.py
    dest: "{{ home }}/.local/bin/"
    mode: 0755
