# ---------------------------------------------------------------------------- #
## \file Makefile
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
SERVICE = shutter

.SUFFIXES:

.PHONY: all
all:

.PHONY: reinstall
reinstall:

include ../../makefiles/service.mk
