# ---------------------------------------------------------------------------- #
## \file gitlab-ci.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
variables:
  PROJECT: project-one
include:
  - local: /../makefiles/package.yml
test:
  stage: test
  script:
    - ./build/$PROJECT &
    - sleep 1
    - ./client.py -q $PROJECT -m click
    - sleep 1
    - ./client.py -q $PROJECT -m status
    - ./client.py -q $PROJECT -m quit
