# ---------------------------------------------------------------------------- #
## \file gitlab-ci.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
variables:
  PROJECT: project-one
  VERSION: 1.0
stages:
  - build
  - tests
  - package
  - install
build:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make --no-print-directory clean
    - make --no-print-directory
tests:
  stage: tests
  script:
    - ./build/$PROJECT &
    - sleep 1
    - ./client.py -q $PROJECT -m click
    - sleep 1
    - ./client.py -q $PROJECT -m status
    - ./client.py -q $PROJECT -m quit
package:
  stage: package
  script:
    - export DEBEMAIL=seb@localhost
    - export DEBFULLNAME=seb
    - mkdir -p build/$PROJECT-$VERSION
    - cd build/$PROJECT-$VERSION
    - dh_make --native --single --yes || true
    - echo "data/$PROJECT /usr/bin/" >debian/$PROJECT.install
    - cp -a ../../debian/* debian/
    - mkdir -p data
    - cp -a ../$PROJECT data/$PROJECT
    - dpkg-buildpackage --no-sign
install:
  stage: install
  script:
    - sudo apt-get reinstall -y ./build/${PROJECT}_${VERSION}_amd64.deb
