# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # name
  config.vm.define "debian10vm"

  # box
  config.vm.box = "debian10vm"
  config.vm.box_url = "./packer_virtualbox-iso_virtualbox.box"

  # gui
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end

  # ssh
  config.ssh.insert_key = false
  config.ssh.private_key_path = "~/.ssh/id_rsa"
  config.ssh.forward_agent = true

  # shared folder
  config.vm.synced_folder 'c:/install-repo', '/home/vagrant/data/install-repo',
    disabled: false,
    create: true,
    owner: "vagrant",
    group: "vagrant",
    mount_options: ["dmode=777,fmode=777"]
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # id_rsa
  config.vm.provision "id_rsa",
    type: "shell", run: "never", privileged: false do |s|
      pub = File.read("#{Dir.home}/.ssh/id_rsa.pub")
      prv = File.read("#{Dir.home}/.ssh/id_rsa")
      s.inline = <<-SHELL
        echo "#{pub}" >~/.ssh/id_rsa.pub
        echo "#{prv}" >~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      SHELL
  end
end
