# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # name
  config.vm.define "debian10vm"

  # box
  config.vm.box = "debian10vm"
  config.vm.box_url = "./packer_virtualbox-iso_virtualbox.box"

  # gui
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end

  # ssh
  config.ssh.insert_key = false
  config.ssh.private_key_path = "~/.ssh/id_rsa"

  # shared folder
  config.vm.synced_folder 'c:/install-repo','/home/vagrant/data/install-repo',
    disabled: false,
    create: true,
    owner: "vagrant",
    group: "vagrant",
    mount_options: ["dmode=777,fmode=777"]

  config.vm.synced_folder ".", "/vagrant", disabled: true
end
