---
- name: screenrc
  blockinfile:
    path: "{{ home }}/.screenrc"
    create: yes
    block: |
      startup_message off
      altscreen on
      bindkey ^[[1;2D prev
      bindkey ^[[1;2C next
      hardstatus alwayslastline "%{= dg} %=%-w%{b ..}%n %t%{= ..}%+w"
      defscrollback 5000
      termcapinfo xterm* ti@:te@
      msgwait 1
      # C-a e
      bind e stuff 'printf "\eklocalhost\e\\\\"'
      shelltitle "localhost"
