---
- name: screenrc
  blockinfile:
    path: "{{ home }}/.screenrc"
    create: yes
    block: |
      startup_message off
      altscreen on
      bindkey ^[[1;2D prev
      bindkey ^[[1;2C next
      hardstatus alwayslastline "%{= dg} %=%-w%{b ..}%n %t%{= ..}%+w"
      defscrollback 5000
      termcapinfo xterm* ti@:te@
      msgwait 1
      # C-a e
      bind e stuff 'printf "\eklocalhost\e\\\\"'
      shelltitle "localhost"

- name: Xresources
  blockinfile:
    path: "{{ home }}/.Xresources"
    create: yes
    marker: ';: {mark} ANSIBLE MANAGED BLOCK'
    block: |
      xterm*font: 9x15
      xterm*foreground: white
      xterm*background: black
      xterm*vt100*translations: #override <Key>F9: secure()
