# ---------------------------------------------------------------------------- #
## \file Makefile
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
EXTRAROLES ?= "['dell7510','upgrade','battery','weather']"
include ../../makefiles/ansible.mk
