# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- name: install dev packages
  apt:
    cache_valid_time: 36000
    install_recommends: no
    name:
      - build-essential
      - chrony
      - chrpath
      - cmake
      - dh-make
      - dpkg-cross
      - expect
      - fakeroot
      - gawk
      - git
      - gdb
      - g++-aarch64-linux-gnu
      - g++-arm-linux-gnueabihf
      - help2man
      - pkg-config
      - python3-pip
      - systemd-coredump  # coredumpctl debug
      - valgrind
      - vim
  become: yes

# https://ibug.io/blog/2026/04/python-venv-at-home/
- name: python venv at home
  lineinfile:
    path: "{{ home }}/.local/pyvenv.cfg"
    line: include-system-site-packages = true

- name: "{{ home }}/.local/bin/python3"
  file:
    path: "{{ home }}/.local/bin/python3"
    src: /usr/bin/python3
    state: link

- name: install python packages
  pip:
    name:
      - pip
      - gitlabci-local
    virtualenv: "{{ home }}/.local"
