# ---------------------------------------------------------------------------- #
## \file Dockerfile
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
FROM i386/debian:trixie-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update\
 && apt-get install -y --no-install-recommends\
 wine32\
