# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- name: vimrc
  blockinfile:
    create: yes
    path: "{{ home }}/.vimrc"
    marker: '" {mark} ANSIBLE MANAGED BLOCK'
    block: |
      set tabstop =4
      set shiftwidth =4
      set softtabstop =4
