# ---------------------------------------------------------------------------- #
## \file install-op-dokuwiki.sh
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
host=mondomaine.net

if notFile /usr/bin/dokuwiki-addsite; then
    apt-get -y install dokuwiki
fi

file=/var/lib/dokuwiki/acl/acl.auth.php
if notGrep "^start" $file; then
    cat >$file <<EOF
# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by Debian postinst script
*       @ALL    0
*       @user   8
start   @ALL    0
start   @user   2
EOF
    chown www-data.www-data $file
fi

file=/etc/dokuwiki/dokuwiki.php
if notGrep "'fr'" $file; then
    sed -i "s/'en'/'fr'/" $file
fi

file=/var/lib/dokuwiki/data/pages/start.txt 
if notFile $file; then
    cat >$file <<EOF
===== Titre =====
**Gras**
  * 1
  * 2
  * 3
[[http://beaugrand.chez.com/|lien]]

> seb: Commentaire

[[nouvellePage|Nouvelle page]]
EOF
    chown www-data.www-data $file
fi

file=/etc/dokuwiki/license.local.php
if notFile $file; then
    cat >$file <<EOF
<?php
\$license['cecill-v2-1'] = array(
    'name' => 'CeCILL 2.1 Free Software license',
    'url'  => 'http://www.cecill.info',
);
EOF
fi

file=/etc/dokuwiki/local.php
if notGrep "cecill" $file; then
    sed -i 's/cc-by-sa/cecill-v2-1/' $file
fi

if [ -f config-pr-.sh ]; then
    source config-pr-.sh
fi

file=/etc/apache2/sites-enabled/dokuwiki.conf
if notFile $file; then
    cat >$file <<EOF
#<VirtualHost _default_:80>
#  ServerName $host
#  Redirect permanent / https://$host
#</VirtualHost>
<IfModule mod_ssl.c>
  <VirtualHost _default_:443>
   #ServerName $host
    DocumentRoot /usr/share/dokuwiki/
    ErrorLog \${APACHE_LOG_DIR}/error.log
    CustomLog \${APACHE_LOG_DIR}/access.log combined
    SSLEngine on
    SSLCertificateFile      /etc/ssl/certs/ssl-cert-snakeoil.pem
    SSLCertificateKeyFile   /etc/ssl/private/ssl-cert-snakeoil.key
   #SSLCertificateFile      /etc/letsencrypt/live/$host/cert.pem
   #SSLCertificateKeyFile   /etc/letsencrypt/live/$host/privkey.pem
   #SSLCertificateChainFile /etc/letsencrypt/live/$host/chain.pem
    <FilesMatch "\.(cgi|shtml|phtml|php)$">
        SSLOptions +StdEnvVars
    </FilesMatch>
    <Directory /usr/lib/cgi-bin>
        SSLOptions +StdEnvVars
    </Directory>
  </VirtualHost>
</IfModule>
EOF
fi

file=/etc/apache2/mods-enabled/ssl.load
if notLink $file; then
    /usr/sbin/a2enmod ssl
fi

file=/etc/apache2/sites-enabled/000-default.conf
if [ -L $file ]; then
    /usr/sbin/a2dissite 000-default
fi

cat <<EOF

Todo:

sudo systemctl reload apache2
firefox http://localhost/dokuwiki/
vi README.md  # domain + cert
sudo vi /etc/apache2/sites-enabled/dokuwiki.conf  # domain + cert
sudo systemctl reload apache2
firefox http://$host/dokuwiki/

EOF
