# ---------------------------------------------------------------------------- #
## \file Makefile
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
BHOST ?= debian13

.PHONY: all
all:
	@echo
	@$(call print-help,Build libjsonrpccpp)
	@echo
	@$(call print-help,Release)
	@echo

include ../makefiles/gitlabci.mk
