# ---------------------------------------------------------------------------- #
## \file gitlab-ci-sbuild.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
variables:
  REPO: mraa
  VERSION: 2.2.0
  REVISION: -1
  URL: https://github.com/sbeaugrand/$REPO.git  # nanopi-neo orange-pi-zero
  #FIXME: rockpi-s
  #URL: https://github.com/radxa/$REPO.git  # rockpi-s
  # vagrant1> vi libmraa/build/mraa/CMakeLists.txt +/v2  # 2.2.0
  # vagrant1> vi libmraa/build/mraa/include/version.h +/gVERSION  # extern
  PKG: lib$REPO
include:
  - local: /../makefiles/sbuild.yml
