# ---------------------------------------------------------------------------- #
## \file gitlab-ci-sbuild.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
variables:
  REPO: mraa
  VERSION: 2.2.0
  REVISION: -1
  CLONE: git clone https://github.com/sbeaugrand/$REPO.git  # nanopi-neo orange-pi-zero
  #FIXME: rockpi-s
  #CLONE: git clone https://github.com/radxa/$REPO.git  # rockpi-s
  # vagrant1> vi libmraa/build/mraa/CMakeLists.txt +/v2  # 2.2.0
  # vagrant1> vi libmraa/build/mraa/include/version.h +/gVERSION  # extern
  PKG: lib$REPO
include:
  - local: /../makefiles/sbuild.yml
build:
  stage: build
  after_script:
    - cd build/$REPO
    - grep -q 'VERSION 3.5' CMakeLists.txt || git apply ../../$REPO.patch
