# ---------------------------------------------------------------------------- #
## \file gitlab-ci.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
variables:
  REPO: mraa
  VERSION: 2.2.0
  URL: https://github.com/sbeaugrand/$REPO.git
  PKG: lib$REPO
include:
  - local: /../makefiles/pbuilder.yml
