# ---------------------------------------------------------------------------- #
## \file gitlab-ci-sbuild.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
variables:
  REPO: mraa
  VERSION: 2.2.0
  REVISION: -1
  CLONE: git clone https://github.com/sbeaugrand/$REPO.git
  PKG: lib$REPO
include:
  - local: /../makefiles/sbuild.yml
build:
  stage: build
  after_script:
    - cd build/$REPO
