# ---------------------------------------------------------------------------- #
## \file Makefile
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
## \note make help
##       ../client.py
##       03a5  0.752V  5866Hz
##       03ab  0.757V  5756Hz
##       03a8  0.754V  5742Hz
##       03aa  0.756V  5835Hz
##       03aa  0.756V  5742Hz
##       03ab  0.757V  5744Hz
##       03aa  0.756V  5792Hz
##       03aa  0.756V  5762Hz
##       03a5  0.752V  5796Hz
##       03ac  0.757V  5774Hz
# ---------------------------------------------------------------------------- #
PROROOT = ..
include $(PROROOT)/rp2350-eth.mk
