# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- name: debian.list
  blockinfile:
    path: /etc/apt/sources.list.d/debian.list
    create: yes
    block: |
      deb http://httpredir.debian.org/debian {{ ansible_distribution_release }} main contrib non-free-firmware
      deb http://httpredir.debian.org/debian/ {{ ansible_distribution_release }}-updates main contrib non-free-firmware
      deb-src http://httpredir.debian.org/debian {{ ansible_distribution_release }} main contrib non-free-firmware
      deb-src http://httpredir.debian.org/debian/ {{ ansible_distribution_release }}-updates main contrib non-free-firmware
  become: yes

- name: sources.list
  lineinfile:
    path: /etc/apt/sources.list
    regexp: '^deb cdrom'
    line: '#'
  become: yes

- name: install localhost packages
  apt:
    cache_valid_time: 36000
    install_recommends: no
    name:
      - aptitude
      - cppcheck
      - curl
      - docker.io
      - dpkg-cross
      - elpa-dpkg-dev-el
      - elpa-cmake-mode
      - elpa-markdown-mode
      - elpa-systemd
      - elpa-yaml-mode
      - emacs-lucid
      - keychain
      - pv
      - rfkill
      - rsync
      - screen
      - sshfs
      - uncrustify
      - xterm
  become: yes

- name: add user to the docker group
  user:
    append: yes
    name: "{{ user }}"
    groups: docker
  become: yes
