# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- name: install localhost packages
  apt:
    cache_valid_time: 36000
    install_recommends: no
    name:
      - aptitude
      - cppcheck
      - curl
      - elpa-cmake-mode
      - elpa-dockerfile-mode
      - elpa-dpkg-dev-el
      - elpa-markdown-mode
      - elpa-systemd
      - elpa-yaml-mode
      - emacs-lucid
      - keychain
      - pv
      - rfkill
      - rsync
      - screen
      - sshfs
      - sshpass  # ansible_password
      - uncrustify
      - xterm
  become: yes
