# ---------------------------------------------------------------------------- #
## \file Makefile
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
PROJECT = geiger
PROROOT = ..

include $(PROROOT)/projects/kicad/doc.mk

build:
	@mkdir $@

include $(PROROOT)/makefiles/tar.mk
