# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
- name: sudoers
  blockinfile:
    path: "/etc/sudoers.d/{{ user }}"
    create: yes
    block: |
      Defaults rootpw
      {{ user }} ALL=(root) ALL
      {{ user }} ALL=({{ user }}) ALL
    mode: 0440
  become: yes
