# ---------------------------------------------------------------------------- #
## \file localhost.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- hosts: localhost
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: /home/{{ user }}
  roles:
    - sudoers
    - packages-localhost
    # Common roles
    - bashrc
    - packages-dev
    - timezone
    - vim
    # Local roles
    - libvirt
    # Desktop roles
    - emacs
    - lxde
    - lxpanel
    - notifications
    - screen
    - screensaver-on
    - xterm
    - role: homepage
      vars:
        src: homepage
    # Optional
    #- dell7510
    #- uncrustify
    #- upgrade
    #- weather
  handlers:
    - name: openbox reconfigure
      command: openbox --reconfigure
    - name: lxpanelctl restart
      command: lxpanelctl restart
