# ---------------------------------------------------------------------------- #
## \file localhost.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- hosts: localhost
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: /home/{{ user }}
  roles:
    - aptsources
    # Common roles
    - bashrc
    - bashrc-root
    - packages-dev
    - timezone
    - vim
    # Local roles
    - packages-localhost
    - gitconfig
    - uncrustify
    # Desktop roles
    - elpa-markdown
    - emacs
    - cinnamon
    - mimeapps
    - notifications
    - screen
    - xterm
    - homepage
  handlers:
    - name: openbox reconfigure
      command: openbox --reconfigure
    - name: lxpanelctl restart
      command: lxpanelctl restart
    - name: xrdb Xresources
      command: xrdb {{ home }}/.Xresources
