# ---------------------------------------------------------------------------- #
## \file package.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
stages:
  - build
  - test
  - package
  - install
  - rbuild
  - rpackage
  - rinstall
  - deploy
variables:
  VERSION: 1.0
  BUILD: Debug
  STRIP: strip
  IMAGE: ubuntu:22.10
  RSYNC: rsync --checksum --delete -a --exclude=*~ --exclude=build -i
  CMAKE: cmake .. -DCMAKE_BUILD_TYPE=$BUILD
build:
  stage: build
  except:
    variables:
      - $PACKAGE =~ '/^lib/'
  script:
    - mkdir -p build
    - cd build
    - $CMAKE
    - make --no-print-directory clean
    - make --no-print-directory -j`nproc`
package:
  stage: package
  except:
    variables:
      - $PACKAGE =~ '/^lib/'
  script:
    - export DEBEMAIL=`git config --global --get user.email`
    - export DEBFULLNAME=`git config --global --get user.name`
    - mkdir -p build/$PROJECT-$VERSION/data
    - cd build/$PROJECT-$VERSION
    - dh_make --native --single --yes || true
    - echo "data/$PROJECT /usr/bin/" >debian/$PROJECT.install
    - cp -a ../$PROJECT data/$PROJECT
    - test ! -d ../../debian || cp -a ../../debian/* debian/
    - dpkg-buildpackage --no-sign
install:
  stage: install
  script:
    - sudo apt-get reinstall -y ./build/${PROJECT}_${VERSION}_amd64.deb
rbuild:
  stage: rbuild
  script:
    - export PROPATH=$(basename `readlink -f .`)
    - cd ../$VM
    - $RSYNC ../$PROPATH/ .vagrant/$PROPATH/
    - $RSYNC ../makefiles/ .vagrant/makefiles/
    - vagrant ssh -c "cd /vagrant/.vagrant/$PROPATH && make build BUILD=$BUILD && (test $BUILD = Debug || $STRIP build/$PROJECT)"
rpackage:
  stage: rpackage
  script:
    - export PROPATH=$(basename `readlink -f .`)
    - cd ../$VM
    - $RSYNC ../$PROPATH/ .vagrant/$PROPATH/
    - $RSYNC ../makefiles/ .vagrant/makefiles/
    - vagrant ssh -c "cd /vagrant/.vagrant/$PROPATH && make package"
rinstall:
  stage: rinstall
  script:
    - export PROPATH=$(basename `readlink -f .`)
    - cd ../$VM
    - vagrant ssh -c "cd /vagrant/.vagrant/$PROPATH && sudo apt-get reinstall -y ./build/${PROJECT}_${VERSION}_amd64.deb"
deploy:
  image: $IMAGE
  stage: deploy
  script:
    - export PROPATH=$(basename `readlink -f .`)
    - cd ../$VM/.vagrant/$PROPATH
    - cp -a build/${PROJECT}_${VERSION}_amd64.deb ../../../$PROPATH/build/
    - test -z "$DEP" || cp -a $DEP ../../../$PROPATH/build/
    - cd -
    - apt update
    - apt-get install -y $DEP ./build/${PROJECT}_${VERSION}_amd64.deb
    - ldd -d -r /usr/bin/$PROJECT
