# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- name: install lubuntu packages
  apt:
    cache_valid_time: 36000
    install_recommends: no
    name:
      - lubuntu-desktop
      - xterm
  become: yes
