# ---------------------------------------------------------------------------- #
## \file gitlab-ci.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
variables:
  PROJECT: project-three
  PACKAGE: binpackage
  VERSION: 1.0
  VMBUILD: lubuntu
include:
  - local: /../makefiles/package.yml
build:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make --no-print-directory clean
    - make --no-print-directory
tests:
  stage: tests
  script:
    - ./build/$PROJECT &
    - sleep 1
    - ../project1/client.py -q $PROJECT -m status
    - ../project1/client.py -q $PROJECT -m quit
