# ---------------------------------------------------------------------------- #
## \file playbook.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- hosts: localhost
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: /home/{{ user }}
  roles:
    - sudoers
    - packages
    #
    - bashrc
    - packages-dev
    - timezone
    - rabbitmq
    - screen
    - vim
    #
    - libvirt
