---
- name: install packages
  apt:
    cache_valid_time: 36000
    install_recommends: no
    name:
      - aptitude
      - cppcheck
      - curl
      - elpa-dpkg-dev-el
      - elpa-markdown-mode
      - elpa-yaml-mode
      - emacs-lucid
      - keychain
      - pv
      - rsync
      - screen
      - uncrustify
      - xterm
  become: yes
