# ---------------------------------------------------------------------------- #
## \file playbook.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- hosts: pis
  vars:
    user: "{{ lookup('env', 'user') }}"
    home: /home/{{ user }}
  roles:
    - sudoers-pi
    - bashrc-pi
    - packages-pi
    - vim
    - screen-remote
    - authorized-keys
    # Optionnal
    - projects-pi
    #- somfi-pi
