# ---------------------------------------------------------------------------- #
## \file install-op-ansible.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- hosts: localhost
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: /home/{{ user }}
  roles:
    - "{{ role }}"
  handlers:
    - name: lxpanelctl restart
      command: lxpanelctl restart
