# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- name: copy owa-html5-notifications
  copy:
    src: "owa-html5-notifications"
    dest: "{{ home }}/.local/share/"
