# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- name: install dev packages for examples
  apt:
    cache_valid_time: 36000
    install_recommends: no
    name:
      - libboost-chrono-dev  # SimpleAmqpClient
      - libboost-system-dev  # SimpleAmqpClient
      - libcpp-httplib-dev
      - libjsonrpccpp-dev
      - libjsonrpccpp-tools
      - libnng-dev
      - libqt5websockets5-dev
      - librabbitmq-dev
      - python3-pika
      - qtbase5-dev
      - rabbitmq-server
      - subversion
  become: yes
