# ---------------------------------------------------------------------------- #
## \file Makefile
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
EXTRAROLES ?= packages-lubuntu,screen
HOST = ubuntu2404b
include ../../makefiles/ansible.mk
