# ---------------------------------------------------------------------------- #
## \file Vagrantfile
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
load "../../makefiles/Vagrantfile"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.define "ubuntu2404b"
  config.vm.hostname = "ubuntu2404b"
  config.vm.provider :libvirt do |libvirt|
    libvirt.management_network_mac = "52:54:00:00:24:04"
  end
end
