# ---------------------------------------------------------------------------- #
## \file install-02-ansible.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- hosts: localhost
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: /home/{{ user }}
  roles:
    - bashrc
    - screen
    - emacs
    - vim
    - xterm
    - lxde
    - mimeapps
    - notifications
  handlers:
    - name: openbox reconfigure
      command: openbox --reconfigure
