# ---------------------------------------------------------------------------- #
## \file gitlab-ci.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
variables:
  PROJECT: project-four
  URL: http://localhost:8383/
include:
  - local: /../makefiles/package.yml
prebuild:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - test -f abstractstubserver.h || jsonrpcstub ../spec.json --cpp-server=AbstractStubServer
test:
  stage: test
  script:
    - build/$PROJECT &
    - sleep 1
    - curl -d '{"jsonrpc":"2.0","method":"status","id":1}' $URL
    - curl -d '{"jsonrpc":"2.0","method":"quit"}' $URL || true
