# ---------------------------------------------------------------------------- #
## \file gitlab-ci.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
variables:
  PROJECT: project-four
include:
  - local: /../makefiles/package.yml
prebuild:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - test -f abstractstubserver.h || jsonrpcstub ../spec.json --cpp-server=AbstractStubServer
test1:
  stage: test
  script:
    ./test1.exp
