# ---------------------------------------------------------------------------- #
## \file gitlab-ci.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
variables:
  PROJECT: project-four
  XC: arm-linux-gnueabihf
  XCVER: 10
  #XCDIR: /vagrant/.vagrant  # rxbuild
include:
  - local: /../makefiles/package.yml
prebuild:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - >
      test -f abstractstubserver.h ||
      jsonrpcstub ../spec.json --cpp-server=AbstractStubServer
test1:
  stage: test
  script:
    - make --no-print-directory
    - ./test1.exp
test2:
  extends: rtest
  script:
    - make --no-print-directory
    - ./test2.exp $IP
test3:
  extends: xtest
  script:
    - make --no-print-directory
    - ./test2.exp $IP
