# ---------------------------------------------------------------------------- #
## \file gitlab-ci.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
variables:
  PROJECT: project-four
  VERSION: 1.0
  VMBUILD: lubuntu
include:
  - local: /../makefiles/package.yml
build:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - test -f abstractstubserver.h || jsonrpcstub ../spec.json --cpp-server=AbstractStubServer
    - cmake ..
    - make --no-print-directory clean
    - make --no-print-directory
tests:
  stage: tests
  script:
    - build/$PROJECT &
    - sleep 1
    - curl -d '{"jsonrpc":"2.0","method":"status","id":1}' http://localhost:8383/
    - curl -d '{"jsonrpc":"2.0","method":"quit"}' http://localhost:8383/ || true
