#!/usr/bin/expect -f
# ---------------------------------------------------------------------------- #
## \file test4.exp
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
set server http://localhost:8383/

spawn build/project-four
set id $spawn_id
sleep 1

spawn php client.php server=$server method=status
expect "ok"
expect eof

spawn php client.php server=$server method=object
expect "("
expect "state] => not ready"
expect "value] => 0"
expect ")"
expect eof

spawn php client.php server=$server method=quit
expect eof

expect -i $id eof
