#!/usr/bin/expect -f
# ---------------------------------------------------------------------------- #
## \file test5.exp
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
set server http://localhost:8383/

spawn build/project-four
set id $spawn_id
sleep 1

spawn client.py $server status
expect "ok"
expect eof

spawn client.py $server object
expect "{"
expect "    \"state\": \"not ready\","
expect "    \"value\": 0"
expect "}"
expect eof

spawn client.py $server quit
expect eof

expect -i $id eof
