# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- name: "{{ home }}/.uncrustify.cfg"
  copy:
    src: uncrustify.cfg
    dest: "{{ home }}/.uncrustify.cfg"
    force: no

- name: "{{ home }}/.local/bin/uncrustify.sh"
  copy:
    src: uncrustify.sh
    dest: "{{ home }}/.local/bin/"
    mode: 0755
