# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- name: copy uncrustify.cfg
  copy:
    src: "uncrustify.cfg"
    dest: "{{ home }}/.uncrustify.cfg"
    force: no
