# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- name: services dir
  file:
    path: "{{ home }}/.local/share/dbus-1/services"
    state: directory

- name: notifications service
  blockinfile:
    path: "{{ home }}/.local/share/dbus-1/services/org.freedesktop.Notifications.service"
    block: |
      [D-BUS Service]
      Name=org.freedesktop.Notifications
      Exec=/usr/lib/notification-daemon/notification-daemon
