# ---------------------------------------------------------------------------- #
## \file gitlab-ci-local.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
variables:
  PROJECT: project-six
include:
  - local: /../makefiles/package.yml
test1:
  stage: test
  script:
    - make --no-print-directory
    - ./test1.exp
test2:
  extends: rtest
  script:
    - make --no-print-directory
    - ./test2.exp $IP
test3:
  extends: stest
  script:
    - make --no-print-directory
    - ./test2.exp $IP
