# ---------------------------------------------------------------------------- #
## \file gitlab-ci.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
variables:
  PROJECT: project-six
include:
  - local: /../makefiles/package.yml
test1:
  stage: test
  script:
    - make --no-print-directory
    - ./test1.exp
test2:
  extends: rtest
  script:
    - make --no-print-directory
    - cd ../$HOST
    - $SSH "cd $USERPATH/$PROPATH && build/server" &
    - sleep 1
    - export IP=`$SSH "hostname -I"`
    - cd -
    - ./test2.exp $IP
