# ---------------------------------------------------------------------------- #
## \file gitlab-ci.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
variables:
  PROJECT: libsimple-amqp-client
  VERSION: 2.5.1
include:
  - local: /../makefiles/package.yml
build:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - test -f v$VERSION.tar.gz || curl -OL https://github.com/alanxz/SimpleAmqpClient/archive/refs/tags/v$VERSION.tar.gz
    - test -d SimpleAmqpClient-$VERSION || tar xzf v$VERSION.tar.gz
    - cmake SimpleAmqpClient-$VERSION
    - make --no-print-directory clean
    - make --no-print-directory
package:
  stage: package
  script:
    - export DEBEMAIL=`git config --global --get user.email`
    - export DEBFULLNAME=`git config --global --get user.name`
    - mkdir -p build/$PROJECT-$VERSION/data
    - cd build/$PROJECT-$VERSION
    - dh_make --native --single --yes || true
    - echo "data/libSimpleAmqpClient.so.7.0.1 /usr/lib/" >debian/$PROJECT.install
    - echo "data/*.h /usr/include/SimpleAmqpClient/" >>debian/$PROJECT.install
    - echo "data/libSimpleAmqpClient.pc /usr/lib/pkgconfig/" >>debian/$PROJECT.install
    - echo "/usr/lib/libSimpleAmqpClient.so.7.0.1 /usr/lib/libSimpleAmqpClient.so.7" >debian/$PROJECT.links
    - echo "/usr/lib/libSimpleAmqpClient.so.7 /usr/lib/libSimpleAmqpClient.so" >>debian/$PROJECT.links
    - |
      sed -i '/^Description: /,${d}' debian/control
    - |
      echo 'Description: Simple C++ Interface to rabbitmq-c' >>debian/control
    - |
      echo ' SimpleAmqpClient is an easy-to-use C++ wrapper around the rabbitmq-c C library.
       It derives inspiration from the puka AMQP library in that it abstracts away the
       underlying AMQP wire concept of channels and uses them as an error/consumer scope.
       This should make writing simple single-threaded AMQP-enabled apps easy.' >>debian/control
    - |
      sed -i 's/Section: .*/Section: libdevel/' debian/control
    - |
      sed -i 's#Homepage: .*#Homepage: https://github.com/alanxz/SimpleAmqpClient#' debian/control
    - cp -a ../*.so.7.0.1 data/
    - cp -a ../SimpleAmqpClient-$VERSION/src/SimpleAmqpClient/*.h data/
    - cp -a ../*.pc data/
    - test ! -d ../../debian || cp -a ../../debian/* debian/
    - dpkg-buildpackage --no-sign
