# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- name: one 21
  blockinfile:
    path: "{{ home }}/.xscreensaver"
    block: |
      mode: one
      selected: 21
