# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- name: "{{ home }}/.bash_login"
  blockinfile:
    path: "{{ home }}/.bash_login"
    create: yes
    block: |
      HISTCONTROL=ignoreboth

      export PS1='\u@\h:\w> '
      alias l='ls'
      alias lrt='ls -lrt'
      alias ls='ls --color=always'
      alias ll='ls -l'
      alias cp='cp -i'
      alias mv='mv -i'
      alias rm='rm -i'
      alias df='df -h'
      alias du='du -h'

      bind '"\e[1;5A": history-search-backward'
      bind '"\e[1;5B": history-search-forward'

      alias rw='sudo mount -o rw,remount /'
      alias ro='sudo mount -o ro,remount /'

      export MP3DIR=/mnt/mp3
      export LC_ALL=C
      export XMMS_PATH=unix:///run/xmms-ipc-ip

      alias volet='sudo /home/$USER/install/debinst/projects/arm/sompi/sompi.sh'

- name: hostname
  hostname:
    name: pi
  become: yes
