# ---------------------------------------------------------------------------- #
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
---
- name: copy rk3308-spi2-spidev.dts
  copy:
    src: rk3308-spi2-spidev.dts
    dest: "{{ home }}/"
  when: ansible_hostname == 'rockpi-s'

- name: install rk3308-spi2-spidev.dts
  command: /usr/sbin/armbian-add-overlay rk3308-spi2-spidev.dts
  args:
    creates: /boot/overlay-user/rk3308-spi2-spidev.dtbo
  when: ansible_hostname == 'rockpi-s'
  become: yes
