# ---------------------------------------------------------------------------- #
## \file .gitlab-ci.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
variables:
  PACKAGE: mps
  RPCLIBS: http://gitlab.local.fr/api/v4/projects/group%2Flibjsonrpccpp
  DIST: stable
prebuild:
  stage: build
  script:
    - update-binfmts --enable qemu-aarch64
    - update-binfmts --enable qemu-arm
build:
  stage: build
  script:
    - dpkg-source -b .
    - >
      test -z "$PRIVATE_TOKEN" ||
      curl -k -L -o artifacts.zip -H "PRIVATE-TOKEN: $PRIVATE_TOKEN"
      ${RPCLIBS}/jobs/artifacts/main/download?job=build%3A%20%5B${ARCH}%5D
    - test -z "$PRIVATE_TOKEN" || unzip -o artifacts.zip -d /sbuild
    - ls -l /sbuild
    - >
      sbuild -v --build=$ARCH --host=$ARCH
      --chroot-mode=schroot -c $DIST-$ARCH-file
      --no-apt-update
      --extra-package=/sbuild
      --build-dir=.
      --no-run-lintian
  parallel:
    matrix:
      - ARCH: [arm64, armhf]
  needs:
    - prebuild
  artifacts:
    paths:
      - "${PACKAGE}_*_$ARCH.deb"
test:
  stage: test
  script:
    - VERSION=`head -n 1 debian/changelog | cut -d ')' -f 1 | cut -d '(' -f 2`
    - lintian --fail-on error,warning    ${PACKAGE}_${VERSION}_*.deb
    - lintian --fail-on error,warning ../${PACKAGE}_${VERSION}.dsc
    - uncrustify.sh -n
    - >
      cppcheck -q --enable=all --suppressions-list=cppcheck.supp
      --template='{id}:{file}:{line} ({severity}) {message}'
      -i build -i build-*
      --suppress=missingIncludeSystem
      --error-exitcode=2
      .
deploy:
  stage: deploy
  script:
    - echo "Define your deployment script"
  environment: staging
