# ---------------------------------------------------------------------------- #
## \file .gitlab-ci.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
variables:
  PROJECT: mps
  PACKAGE: mps
  DIST: stable
  ARCH: armhf
build:
  stage: build
  script:
    - VERSION=`head -n 1 debian/changelog | cut -d ')' -f 1 | cut -d '(' -f 2`
    - dpkg-source -b .
    - update-binfmts --enable qemu-arm
    - >
      sbuild -D -v --build=$ARCH --host=$ARCH --chroot-mode=schroot
      -c $DIST-$ARCH-file --no-apt-update
      --build-dir=/sbuild --extra-package=/sbuild
    - cp -a /sbuild/${PACKAGE}_${VERSION}_$ARCH.deb .
  artifacts:
    paths:
      - "${PACKAGE}_*_$ARCH.deb"
test:
  stage: test
  script:
    - VERSION=`head -n 1 debian/changelog | cut -d ')' -f 1 | cut -d '(' -f 2`
    - cd ..
    - lintian --fail-on error,warning ${PACKAGE}_${VERSION}_$ARCH.deb
    - lintian --fail-on error,warning ${PACKAGE}_${VERSION}.dsc
deploy:
  stage: deploy
  script:
    - echo "Define your deployment script"
  environment: staging
