# ---------------------------------------------------------------------------- #
## \file gitlab-ci.yml
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
variables:
  PROJECT: mps
  lserver: http://localhost:8383
  musicdir: /data/mp3
  verbose: -v
include:
  - local: /../makefiles/package.yml
prebuild:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - >
      test -f abstractstubserver.h ||
      jsonrpcstub ../spec.json --cpp-server=AbstractStubServer
prexbuild:
  stage: xbuild
  script:
    - mkdir -p build
    - cd build
    - >
      test -f abstractstubserver.h ||
      jsonrpcstub ../spec.json --cpp-server=AbstractStubServer
prepackage:
  stage: package
  script:
    - mkdir -p $BDIR/$PROJECT-$VERSION/data
    - cd $BDIR/$PROJECT-$VERSION
    - test ! -f ../mpserver || cp -a ../mpserver data/
    - test ! -f ../mpclient || cp -a ../mpclient data/
test1:
  stage: test
  script:
    - make --no-print-directory
    - systemctl -q is-active mpd || sudo systemctl start mpd
    - ./test1.py $lserver $musicdir $verbose
